/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;



public partial class JugadorNoEncontrado : TException, TBase
{
  private int _idJugador;
  private string _mensaje;

  public int IdJugador
  {
    get
    {
      return _idJugador;
    }
    set
    {
      __isset.idJugador = true;
      this._idJugador = value;
    }
  }

  public string Mensaje
  {
    get
    {
      return _mensaje;
    }
    set
    {
      __isset.mensaje = true;
      this._mensaje = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool idJugador;
    public bool mensaje;
  }

  public JugadorNoEncontrado()
  {
  }

  public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32)
            {
              IdJugador = await iprot.ReadI32Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.String)
            {
              Mensaje = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("JugadorNoEncontrado");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      if (__isset.idJugador)
      {
        field.Name = "idJugador";
        field.Type = TType.I32;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI32Async(IdJugador, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (Mensaje != null && __isset.mensaje)
      {
        field.Name = "mensaje";
        field.Type = TType.String;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteStringAsync(Mensaje, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    var other = that as JugadorNoEncontrado;
    if (other == null) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.idJugador == other.__isset.idJugador) && ((!__isset.idJugador) || (System.Object.Equals(IdJugador, other.IdJugador))))
      && ((__isset.mensaje == other.__isset.mensaje) && ((!__isset.mensaje) || (System.Object.Equals(Mensaje, other.Mensaje))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if(__isset.idJugador)
        hashcode = (hashcode * 397) + IdJugador.GetHashCode();
      if(__isset.mensaje)
        hashcode = (hashcode * 397) + Mensaje.GetHashCode();
    }
    return hashcode;
  }

  public override string ToString()
  {
    var sb = new StringBuilder("JugadorNoEncontrado(");
    bool __first = true;
    if (__isset.idJugador)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("IdJugador: ");
      sb.Append(IdJugador);
    }
    if (Mensaje != null && __isset.mensaje)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Mensaje: ");
      sb.Append(Mensaje);
    }
    sb.Append(")");
    return sb.ToString();
  }
}

